id = "CColors"
name = "CColors"
version = "0.0.1"
schema_version = 1
authors = ["Stalker17 <roadsidepicniczkp@protonmail.com>"]
description = "A cyberpunk theme for Zed, forked from OutrunZedTheme"
repository = "https://github.com/Stalker17/CColors-ZedTheme"
